quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password12
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/hrms

quarkus.log.category."org.postgresql".level=DEBUG
quarkus.log.category."io.agroal".level=DEBUG

quarkus.hibernate-orm.schema-management.strategy=none

%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.devservices.enabled=true
%dev.quarkus.datasource.devservices.db-name=hrms_db

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

#JWT in Quarkus uses RSA keys — a private key to sign tokens, a public key to verify them. Run this in your terminal once:
# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=hrms-app
smallrye.jwt.sign.key.location=privateKey.pem

# Security
quarkus.http.auth.permission.public.paths=/api/auth/login,/swagger/*,/openapi,/api/test
quarkus.http.auth.permission.public.policy=permit

# Everything else requires JWT
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated

 # OpenAPI
 quarkus.smallrye-openapi.path=/openapi

# # Swagger UI
 quarkus.swagger-ui.always-include=true
 quarkus.swagger-ui.path=/swagger